### ISSUE TITLE
Add Whatsapp beta Support

### ISSUE THREAD

**Issue by rsoorajs** [UKnowWhoIm/whatsapp-telegram-bridge#13]
New Whatsapp Beta added Multi device Support.Usage of Whatsapp web even without need our mobile always online.We need to join a feature called "Multi-device beta" to enable this support in Whatsapp beta.But When this feature is on,QR code failed to read,when feature is off, QR code reads.but only we can stay online in Whatsapp web is using this feature on.so kindly fix this asap.

**Comment by UKnowWhoIm** [comment]
@rsoorajs I currently don't have access to Whatsapp Beta to debug this issue. If you can work on it feel free to do it.

**Comment by UKnowWhoIm** [comment]
@rsoorajs I've used the [Venom API](https://github.com/orkestral/venom) for WhatsApp side of things. You could open an issue there along with your debug information.
There seems to be an open [thread](https://github.com/orkestral/venom/issues/1101) on it

**Comment by rsoorajs** [comment]
> @rsoorajs I've used the [Venom API](https://github.com/orkestral/venom) for WhatsApp side of things. You could open an issue there along with your debug information.
> There seems to be an open [thread](https://github.com/orkestral/venom/issues/1101) on it

yeah i will follow them.thank you

**Comment by rsoorajs** [comment]
working

**Comment by JimmyBastos** [comment]
+1
